- client: go-ethereum
  nametag: prague-devnet-4
  dockerfile: git
  build_args:
    github: lightclient/go-ethereum
    tag: prague-devnet-4

- client: nethermind
  nametag: prague-devnet-4
  dockerfile: git
  build_args:
    github: NethermindEth/nethermind
    tag: pectra_devnet_4

- client: reth
  nametag: prague-devnet-4
  dockerfile: git
  build_args:
    github: paradigmxyz/reth
    tag: onbjerg/devnet-4

- client: besu
  nametag: prague-devnet-4
  dockerfile: git
  build_args:
    github: hyperledger/besu
    tag: pectra-devnet-4

- client: ethereumjs
  nametag: prague-devnet-4
  build_args:
    github: ethereumjs/ethereumjs-monorepo
    tag: 7702-devnet-4-plus-t8ntool

- client: erigon
  nametag: prague-devnet-4
  dockerfile: git
  build_args:
    github: erigontech/erigon
    tag: som/remove_deposit_req
